# app/schemas/enums_historico.py
from enum import StrEnum


class TipoEventoCodigoEnum(StrEnum):
    CLIENTE_ACTUALIZADO = "CLIENTE_ACTUALIZADO"
    VISITA_REGISTRADA = "VISITA_REGISTRADA"
    PEDIDO_CONFIRMADO = "PEDIDO_CONFIRMADO"
    PEDIDO_CREADO = "PEDIDO_CREADO"
    INTERES_APLICADO = "INTERES_APLICADO"
    PAGO_DEUDA_REGISTRADO = "PAGO_DEUDA_REGISTRADO"
    DEUDA_CANCELADA_TOTAL = "DEUDA_CANCELADA_TOTAL"
    DISPENSER_ALTA = "DISPENSER_ALTA"
    DISPENSER_PAGO = "DISPENSER_PAGO"
    DISPENSER_DADO_DE_BAJA = "DISPENSER_DADO_DE_BAJA"
    CAMBIO_PRECIO_DISPENSER = "CAMBIO_PRECIO_DISPENSER"
    PERIODO_VENCIDO = "PERIODO_VENCIDO"
    # Más adelante:
    # PEDIDO_CREADO = "PEDIDO_CREADO"
    # PEDIDO_ACTUALIZADO = "PEDIDO_ACTUALIZADO"
