"""Agregamos el atributo orden en la tabla cliente_dia_semana

Revision ID: 40e5d84473a6
Revises: e61084d8ad4a
Create Date: 2025-11-08 19:06:26.735595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e5d84473a6'
down_revision: Union[str, Sequence[str], None] = 'e61084d8ad4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # En Postgres podemos usar IF NOT EXISTS
    op.execute(
        """
        ALTER TABLE cliente_dia_semana
        ADD COLUMN IF NOT EXISTS orden SMALLINT
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente_dia_semana', 'orden')
    # ### end Alembic commands ###
