"""base sin schema

Revision ID: e61084d8ad4a
Revises: 
Create Date: 2025-11-08 15:50:29.783761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61084d8ad4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dia_semana',
    sa.Column('id_dia', sa.SmallInteger(), nullable=False),
    sa.Column('nombre_dia', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id_dia')
    )
    op.create_table('empresa',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id_empresa')
    )
    op.create_table('lista_de_precios',
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_lista')
    )
    op.create_table('medio_pago',
    sa.Column('id_medio_pago', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_medio_pago')
    )
    op.create_table('persona',
    sa.Column('dni', sa.BigInteger(), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('dni')
    )
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('litros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo_dispenser', sa.String(length=50), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('tipo_evento',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_table('tipo_movimiento_caja',
    sa.Column('id_tipo_movimiento', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_movimiento')
    )
    op.create_table('caja_empresa',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_tipo_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_medio_pago', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_medio_pago'], ['medio_pago.id_medio_pago'], ),
    sa.ForeignKeyConstraint(['id_tipo_movimiento'], ['tipo_movimiento_caja.id_tipo_movimiento'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_table('camion_reparto',
    sa.Column('patente', sa.String(length=20), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('patente')
    )
    op.create_table('cliente',
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('dni', sa.BigInteger(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dni'], ['persona.dni'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('legajo')
    )
    op.create_table('cuenta_bancaria_empresa',
    sa.Column('id_cuenta', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('titular_cuenta', sa.String(length=150), nullable=True),
    sa.Column('cbu', sa.String(length=30), nullable=True),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.Column('numero_de_cuenta', sa.String(length=40), nullable=True),
    sa.Column('tipo_cuenta', sa.String(length=40), nullable=True),
    sa.Column('banco', sa.String(length=80), nullable=True),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_cuenta')
    )
    op.create_table('empleado',
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('dni', sa.BigInteger(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dni'], ['persona.dni'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('legajo')
    )
    op.create_index(op.f('ix_empleado_id_empresa'), 'empleado', ['id_empresa'], unique=False)
    op.create_table('lista_precio_producto',
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_lista'], ['lista_de_precios.id_lista'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_lista', 'id_producto')
    )
    op.create_table('stock',
    sa.Column('id_stock', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_stock')
    )
    op.create_table('cliente_cuenta',
    sa.Column('id_cuenta', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('deuda', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('tipo_de_cuenta', sa.String(length=50), nullable=True),
    sa.Column('numero_bidones', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['legajo'], ['cliente.legajo'], ),
    sa.PrimaryKeyConstraint('id_cuenta')
    )
    op.create_table('cliente_dia_semana',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_dia', sa.SmallInteger(), nullable=False),
    sa.Column('turno_visita', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.legajo'], ),
    sa.ForeignKeyConstraint(['id_dia'], ['dia_semana.id_dia'], ),
    sa.PrimaryKeyConstraint('id_cliente', 'id_dia')
    )
    op.create_table('direccion_cliente',
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('entre_calle1', sa.String(length=100), nullable=True),
    sa.Column('entre_calle2', sa.String(length=100), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('latitud_longitud', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['legajo'], ['cliente.legajo'], ),
    sa.PrimaryKeyConstraint('id_direccion')
    )
    op.create_table('documentos',
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=50), nullable=True),
    sa.Column('url_archivo', sa.String(length=500), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['legajo'], ['cliente.legajo'], ),
    sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('historico',
    sa.Column('id_historico', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['tipo_evento.id_evento'], ),
    sa.ForeignKeyConstraint(['legajo'], ['cliente.legajo'], ),
    sa.PrimaryKeyConstraint('id_historico')
    )
    op.create_table('mail_cliente',
    sa.Column('id_mail', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['legajo'], ['cliente.legajo'], ),
    sa.PrimaryKeyConstraint('id_mail')
    )
    op.create_table('producto_cliente',
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.ForeignKeyConstraint(['legajo'], ['cliente.legajo'], ),
    sa.PrimaryKeyConstraint('legajo', 'id_producto')
    )
    op.create_table('telefono_cliente',
    sa.Column('id_telefono', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('nro_telefono', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['legajo'], ['cliente.legajo'], ),
    sa.PrimaryKeyConstraint('id_telefono')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=100), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('legajo_empleado', sa.Integer(), nullable=True),
    sa.Column('legajo_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['legajo_cliente'], ['cliente.legajo'], ),
    sa.ForeignKeyConstraint(['legajo_empleado'], ['empleado.legajo'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('reparto_dia',
    sa.Column('id_repartodia', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('total_recaudado', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('total_efectivo', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('total_virtual', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_repartodia')
    )
    op.create_table('usuario_rol',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol')
    )
    op.create_table('cliente_reparto_dia',
    sa.Column('id_repartodia', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('bidones_entregado', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('monto_abonado', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('estado_de_la_visita', sa.String(length=30), nullable=True),
    sa.Column('turno_de_la_visita', sa.String(length=20), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_repartodia'], ['reparto_dia.id_repartodia'], ),
    sa.ForeignKeyConstraint(['legajo'], ['cliente.legajo'], ),
    sa.PrimaryKeyConstraint('id_repartodia', 'legajo')
    )
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('id_medio_pago', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_repartodia', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_abonado', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_medio_pago'], ['medio_pago.id_medio_pago'], ),
    sa.ForeignKeyConstraint(['id_repartodia'], ['reparto_dia.id_repartodia'], ),
    sa.ForeignKeyConstraint(['legajo'], ['cliente.legajo'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('recorrido',
    sa.Column('id_recorrido', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_repartodia', sa.Integer(), nullable=False),
    sa.Column('id_camion', sa.String(length=20), nullable=False),
    sa.Column('dinero_inicial', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('stock_inicial', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_camion'], ['camion_reparto.patente'], ),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.legajo'], ),
    sa.ForeignKeyConstraint(['id_repartodia'], ['reparto_dia.id_repartodia'], ),
    sa.PrimaryKeyConstraint('id_recorrido')
    )
    op.create_table('movimiento_stock',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_recorrido', sa.Integer(), nullable=True),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=30), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.ForeignKeyConstraint(['id_recorrido'], ['recorrido.id_recorrido'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_table('pedido_producto',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_pedido', 'id_producto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_producto')
    op.drop_table('movimiento_stock')
    op.drop_table('recorrido')
    op.drop_table('pedido')
    op.drop_table('cliente_reparto_dia')
    op.drop_table('usuario_rol')
    op.drop_table('reparto_dia')
    op.drop_table('usuario')
    op.drop_table('telefono_cliente')
    op.drop_table('producto_cliente')
    op.drop_table('mail_cliente')
    op.drop_table('historico')
    op.drop_table('documentos')
    op.drop_table('direccion_cliente')
    op.drop_table('cliente_dia_semana')
    op.drop_table('cliente_cuenta')
    op.drop_table('stock')
    op.drop_table('lista_precio_producto')
    op.drop_index(op.f('ix_empleado_id_empresa'), table_name='empleado')
    op.drop_table('empleado')
    op.drop_table('cuenta_bancaria_empresa')
    op.drop_table('cliente')
    op.drop_table('camion_reparto')
    op.drop_table('caja_empresa')
    op.drop_table('tipo_movimiento_caja')
    op.drop_table('tipo_evento')
    op.drop_table('rol')
    op.drop_table('producto')
    op.drop_table('persona')
    op.drop_table('medio_pago')
    op.drop_table('lista_de_precios')
    op.drop_table('empresa')
    op.drop_table('dia_semana')
    # ### end Alembic commands ###
