"""crear tabla visita

Revision ID: eb0d71ad3c76
Revises: 8c228284a4e9
Create Date: 2025-11-25 16:29:04.448272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0d71ad3c76'
down_revision: Union[str, Sequence[str], None] = '8c228284a4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visita',
    sa.Column('id_visita', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['legajo'], ['cliente.legajo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_visita')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visita')
    # ### end Alembic commands ###
